version: '3.8'

services:
  fim:
    build: .
    container_name: fim
    user: "33:33"
    restart: unless-stopped
    volumes:
      - .:/var/www/html
    networks:
      - nusmart-net

  fim-nginx:
    image: nginx:alpine
    container_name: fim-nginx
    restart: unless-stopped
    depends_on:
      - fim
    volumes:
      - .:/var/www/html # Peta seluruh projek ke dalam kontena
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:rw
      - ./html:/usr/share/nginx/html:rw #
    environment:
      - VIRTUAL_HOST=fim-dev.nusmart.my
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=fim-dev.nusmart.my
    networks:
      - nusmart-net

networks:
  nusmart-net:
    external: true
    name: nusmart-net
